language: go
go:
- 1.13.x
env:
  global:
  - GO111MODULE=on
jobs:
  include:
  - stage: build
    install: []
    script:
    - scripts/ci scripts/generate
    - scripts/ci scripts/build-all
    - scripts/ci scripts/test
  - stage: release
    if: branch = master and tag =~ ^v
    install: []
    script:
    - scripts/ci scripts/dist-all
    - scripts/ci scripts/release-all
